name: mumps-ide
base: core22
version: '1.0'
summary: MUMPS Language IDE - Professional development environment for MUMPS/M
description: |
  MUMPS Language IDE is a modern, feature-rich integrated development
  environment for MUMPS (M) programming language. Built with Electron
  and Monaco Editor, it provides syntax highlighting, debugging, Docker
  and SSH connectivity, and comprehensive project management.

  Features:
  - Monaco-based code editor with MUMPS syntax highlighting
  - Run and debug MUMPS code with YottaDB integration
  - Docker and SSH connection support
  - Universal Docker mode - works with any container
  - Git integration for version control
  - Integrated terminal with xterm.js
  - Project management and file organization
  - Search and replace across files
  - Extension system for customization

  Developed by Ahmad Alkhalaileh

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  mumps-ide:
    command: mumps-ide
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - browser-support
      - ssh-keys
      - docker
      - removable-media
    environment:
      DISABLE_WAYLAND: '1'
      ELECTRON_TRASH: gio

parts:
  mumps-ide:
    plugin: dump
    source: .
    build-packages:
      - nodejs
      - npm
    stage-packages:
      - libnss3
      - libnspr4
      - libxss1
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libxtst6
      - libappindicator3-1
      - libsecret-1-0
    override-build: |
      # Copy all application files to install directory
      mkdir -p $SNAPCRAFT_PART_INSTALL/app

      # Copy all files
      cp -r $SNAPCRAFT_PART_SRC/* $SNAPCRAFT_PART_INSTALL/app/ || true

      # Remove unwanted directories
      rm -rf $SNAPCRAFT_PART_INSTALL/app/node_modules
      rm -rf $SNAPCRAFT_PART_INSTALL/app/.git
      rm -rf $SNAPCRAFT_PART_INSTALL/app/snap
      rm -f $SNAPCRAFT_PART_INSTALL/app/*.log

      # Install production dependencies
      cd $SNAPCRAFT_PART_INSTALL/app
      npm install --production --ignore-scripts

      # Create launcher script
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat > $SNAPCRAFT_PART_INSTALL/bin/mumps-ide << 'EOF'
      #!/bin/bash
      exec "$SNAP/app/node_modules/.bin/electron" "$SNAP/app" "$@" --no-sandbox --disable-gpu
      EOF

      chmod +x $SNAPCRAFT_PART_INSTALL/bin/mumps-ide

  desktop-file:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui
      cat > $SNAPCRAFT_PART_INSTALL/meta/gui/mumps-ide.desktop << EOF
      [Desktop Entry]
      Name=MUMPS IDE
      Comment=Professional IDE for MUMPS/M Programming
      Exec=mumps-ide %U
      Icon=\${SNAP}/meta/gui/icon.png
      Terminal=false
      Type=Application
      Categories=Development;IDE;
      StartupWMClass=MUMPS IDE
      EOF

  icon:
    plugin: nil
    override-build: |
      # Create a simple icon (you can replace this with a proper icon file)
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui
      # For now, we'll create a placeholder
      # You should add your actual icon.png to the project
      # cp icon.png $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.ahmadalkhalaileh.mumpsIDE
