name: mumps-studio
base: core22
version: '1.1'
title: Mumps Studio
summary: Mumps Studio - Professional development environment for MUMPS/M
license: Proprietary
contact: ahmad@example.com
website: https://github.com/AhmadAlkhalaileh/mumpsIDE
source-code: https://github.com/AhmadAlkhalaileh/mumpsIDE
issues: https://github.com/AhmadAlkhalaileh/mumpsIDE/issues
icon: icon.png
description: |
  Mumps Studio is a modern, feature-rich integrated development
  environment for MUMPS (M) programming language. Built with Electron
  and Monaco Editor, it provides syntax highlighting, debugging, Docker
  and SSH connectivity, and comprehensive project management.

  Features:
  - Monaco-based code editor with MUMPS syntax highlighting
  - Run and debug MUMPS code with YottaDB integration
  - Docker and SSH connection support
  - Universal Docker mode - works with any container
  - Git integration for version control
  - Integrated terminal with xterm.js
  - Project management and file organization
  - Search and replace across files
  - Extension system for customization

  Developed by Ahmad Alkhalaileh

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  mumps-studio:
    command: bin/mumps-studio
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - browser-support
      - ssh-keys
      - docker-support
      - removable-media
    environment:
      DISABLE_WAYLAND: '1'
      ELECTRON_TRASH: gio

parts:
  mumps-studio:
    plugin: dump
    source: .

    build-packages:
      - rsync

    override-build: |
      set -eux

      echo "=== Starting Mumps Studio Build ==="

      # Navigate to source
      cd "${SNAPCRAFT_PART_SRC}"

      echo "=== Current directory: $(pwd) ==="
      echo "=== Checking for node_modules ==="

      if [ ! -d "node_modules" ] || [ ! -f "node_modules/electron/dist/electron" ]; then
        echo "ERROR: node_modules not found or incomplete!"
        echo "Please run this command BEFORE building the snap:"
        echo ""
        echo "  npm install --include=dev"
        echo ""
        echo "This will install all dependencies including Electron locally."
        echo "Then run the snap build again."
        exit 1
      fi

      echo "=== Verifying electron installation ==="
      ls -lh node_modules/electron/dist/electron

      echo "=== Copying application to snap ==="
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/app"

      # Copy everything except snap directory and build artifacts
      rsync -av \
        --exclude='.git' \
        --exclude='.github' \
        --exclude='snap' \
        --exclude='parts' \
        --exclude='prime' \
        --exclude='stage' \
        --exclude='docs' \
        --exclude='.gitignore' \
        --exclude='.gitattributes' \
        --exclude='*.log' \
        --exclude='*.snap' \
        --exclude='.snapcraft' \
        --exclude='*.md' \
        "${SNAPCRAFT_PART_SRC}"/ \
        "${SNAPCRAFT_PART_INSTALL}/app/"

      echo "=== Installing icon ==="
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/meta/gui"

      # Snap desktop integration expects the desktop file Icon= name to match
      # a file in meta/gui (e.g. Icon=mumps-studio -> meta/gui/mumps-studio.png).
      ICON_DST_NAME="mumps-studio"
      ICON_DST_PNG="${SNAPCRAFT_PART_INSTALL}/meta/gui/${ICON_DST_NAME}.png"
      ICON_DST_FALLBACK="${SNAPCRAFT_PART_INSTALL}/meta/gui/icon.png"

      # Try to find and copy icon
      ICON_FOUND=false
      for icon_path in \
        "${SNAPCRAFT_PART_SRC}/icon.png" \
        "${SNAPCRAFT_PART_SRC}/assets/icon.png" \
        "${SNAPCRAFT_PART_SRC}/resources/icon.png"; do
        if [ -f "${icon_path}" ]; then
          cp -f "${icon_path}" "${ICON_DST_PNG}"
          cp -f "${icon_path}" "${ICON_DST_FALLBACK}"
          echo "Icon copied from: ${icon_path}"
          ICON_FOUND=true
          break
        fi
      done

      if [ "${ICON_FOUND}" = "false" ]; then
        echo "Warning: No icon.png found, creating placeholder"
        printf '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > "${ICON_DST_PNG}"
        cp -f "${ICON_DST_PNG}" "${ICON_DST_FALLBACK}"
      fi

      echo "=== Creating desktop file ==="
      cat > "${SNAPCRAFT_PART_INSTALL}/meta/gui/mumps-studio.desktop" <<"EOF"
      [Desktop Entry]
      Name=Mumps Studio
      Comment=Professional IDE for MUMPS/M Programming
      Exec=mumps-studio %U
      Icon=${SNAP}/meta/gui/mumps-studio.png
      Terminal=false
      Type=Application
      Categories=Development;IDE;
      StartupWMClass=mumps-studio
      EOF
      sed -i 's/^      //' "${SNAPCRAFT_PART_INSTALL}/meta/gui/mumps-studio.desktop"

      echo "=== Creating launcher script ==="
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/bin"

      cat > "${SNAPCRAFT_PART_INSTALL}/bin/mumps-studio" <<"LAUNCHER_EOF"
      #!/bin/sh
      exec "$SNAP/app/node_modules/electron/dist/electron" "$SNAP/app" --no-sandbox "$@"
      LAUNCHER_EOF
      sed -i 's/^      //' "${SNAPCRAFT_PART_INSTALL}/bin/mumps-studio"

      chmod +x "${SNAPCRAFT_PART_INSTALL}/bin/mumps-studio"

      echo "=== Build complete ==="
      echo "Installed files:"
      ls -la "${SNAPCRAFT_PART_INSTALL}/bin/"
      echo "App directory size:"
      du -sh "${SNAPCRAFT_PART_INSTALL}/app" || true

    stage-packages:
      - libnss3
      - libnspr4
      - libxss1
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libxtst6
      - libappindicator3-1
      - libsecret-1-0
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libdrm2
      - libgbm1
      - libgtk-3-0
      - ca-certificates
      - fonts-liberation
      - fonts-noto
      - fontconfig
      - libfontconfig1
      - adwaita-icon-theme
      - gnome-themes-standard
      - git
      - openssh-client
      - sshpass
      - docker.io
