name: mumps-ide
base: core22
version: '1.0'
summary: MUMPS Language IDE - Professional development environment for MUMPS/M
description: |
  MUMPS Language IDE is a modern, feature-rich integrated development
  environment for MUMPS (M) programming language. Built with Electron
  and Monaco Editor, it provides syntax highlighting, debugging, Docker
  and SSH connectivity, and comprehensive project management.

  Features:
  - Monaco-based code editor with MUMPS syntax highlighting
  - Run and debug MUMPS code with YottaDB integration
  - Docker and SSH connection support
  - Universal Docker mode - works with any container
  - Git integration for version control
  - Integrated terminal with xterm.js
  - Project management and file organization
  - Search and replace across files
  - Extension system for customization

  Developed by Ahmad Alkhalaileh

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  mumps-ide:
    command: bin/mumps-ide
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - browser-support
      - ssh-keys
      - docker
      - removable-media
    environment:
      DISABLE_WAYLAND: '1'
      ELECTRON_TRASH: gio

parts:
  mumps-ide:
    plugin: dump
    source: ..
    organize:
      "*": app/
    prime:
      - -app/.git/**
      - -app/snap/**
      - -app/**/*.log
      - -app/*.log

    # Needed to build native node modules (node-pty, etc.) inside LXD
    build-packages:
      - python3
      - make
      - g++
      - pkg-config

    after:
      - node

    override-build: |
      set -eux

      # Add our custom Node to PATH
      export PATH="$SNAPCRAFT_STAGE/bin:$PATH"

      # Install ALL dependencies (including devDependencies) so Electron is included
      cd "$SNAPCRAFT_PART_SRC"
      export NODE_ENV=development
      export NPM_CONFIG_PRODUCTION=false
      npm ci --include=dev

      # Ensure icon ends up in the right place for the desktop file
      mkdir -p "$SNAPCRAFT_PART_INSTALL/meta/gui"
      if [ -f "$SNAPCRAFT_PART_SRC/icon.png" ]; then
        cp -f "$SNAPCRAFT_PART_SRC/icon.png" "$SNAPCRAFT_PART_INSTALL/meta/gui/icon.png"
      elif [ -f "$SNAPCRAFT_PART_SRC/app/icon.png" ]; then
        cp -f "$SNAPCRAFT_PART_SRC/app/icon.png" "$SNAPCRAFT_PART_INSTALL/meta/gui/icon.png"
      fi

      # Desktop file
      cat > "$SNAPCRAFT_PART_INSTALL/meta/gui/mumps-ide.desktop" << 'EOF'
      [Desktop Entry]
      Name=MUMPS IDE
      Comment=Professional IDE for MUMPS/M Programming
      Exec=mumps-ide %U
      Icon=${SNAP}/meta/gui/icon.png
      Terminal=false
      Type=Application
      Categories=Development;IDE;
      StartupWMClass=MUMPS IDE
      EOF

      # Launcher script (run the real Electron binary inside electron package)
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      cat > "$SNAPCRAFT_PART_INSTALL/bin/mumps-ide" << 'EOF'
      #!/bin/sh
      set -eu
      exec "$SNAP/app/node_modules/electron/dist/electron" "$SNAP/app" "$@" --no-sandbox --disable-gpu
      EOF
      chmod +x "$SNAPCRAFT_PART_INSTALL/bin/mumps-ide"

      snapcraftctl build

    stage-packages:
      - libnss3
      - libnspr4
      - libxss1
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libxtst6
      - libappindicator3-1
      - libsecret-1-0

  node:
    plugin: nil
    source: https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.xz
    override-build: |
      set -eux
      tar xf $SNAPCRAFT_PART_SRC/node-v18.18.0-linux-x64.tar.xz
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib
      mkdir -p $SNAPCRAFT_PART_INSTALL/include
      mkdir -p $SNAPCRAFT_PART_INSTALL/share
      cp -r node-v18.18.0-linux-x64/bin/* $SNAPCRAFT_PART_INSTALL/bin/
      cp -r node-v18.18.0-linux-x64/lib/* $SNAPCRAFT_PART_INSTALL/lib/
      cp -r node-v18.18.0-linux-x64/include/* $SNAPCRAFT_PART_INSTALL/include/
      cp -r node-v18.18.0-linux-x64/share/* $SNAPCRAFT_PART_INSTALL/share/

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.ahmadalkhalaileh.mumpsIDE
