name: mumps-ide
base: core22
version: '1.4'
title: MUMPS IDE
summary: MUMPS Language IDE - Professional development environment for MUMPS/M
license: Proprietary
contact: ahmad@example.com
website: https://github.com/ahmadalkhalaileh
description: |
  MUMPS Language IDE is a modern, feature-rich integrated development
  environment for MUMPS (M) programming language. Built with Electron
  and Monaco Editor, it provides syntax highlighting, debugging, Docker
  and SSH connectivity, and comprehensive project management.

  Features:
  - Monaco-based code editor with MUMPS syntax highlighting
  - Run and debug MUMPS code with YottaDB integration
  - Docker and SSH connection support
  - Universal Docker mode - works with any container
  - Git integration for version control
  - Integrated terminal with xterm.js
  - Project management and file organization
  - Search and replace across files
  - Extension system for customization

  Developed by Ahmad Alkhalaileh

grade: stable
confinement: devmode

architectures:
  - build-on: amd64

apps:
  mumps-ide:
    command: bin/mumps-ide
    environment:
      DISABLE_WAYLAND: '1'
      ELECTRON_TRASH: gio
      ELECTRON_ENABLE_LOGGING: '1'
      ELECTRON_FORCE_IS_PACKAGED: '1'

parts:
  mumps-ide:
    plugin: dump
    source: .

    build-packages:
      - rsync

    override-build: |
      set -eux

      echo "=== Starting MUMPS IDE Build ==="

      # Navigate to source
      cd "${SNAPCRAFT_PART_SRC}"

      echo "=== Current directory: $(pwd) ==="
      echo "=== Checking for node_modules ==="

      if [ ! -d "node_modules" ] || [ ! -f "node_modules/electron/dist/electron" ]; then
        echo "ERROR: node_modules not found or incomplete!"
        echo "Please run this command BEFORE building the snap:"
        echo ""
        echo "  npm install --include=dev"
        echo ""
        echo "This will install all dependencies including Electron locally."
        echo "Then run the snap build again."
        exit 1
      fi

      echo "=== Verifying electron installation ==="
      ls -lh node_modules/electron/dist/electron

      echo "=== Copying application to snap ==="
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/app"

      # Copy everything except snap directory and build artifacts
      rsync -av \
        --exclude='.git' \
        --exclude='.github' \
        --exclude='snap' \
        --exclude='parts' \
        --exclude='prime' \
        --exclude='stage' \
        --exclude='docs' \
        --exclude='.gitignore' \
        --exclude='.gitattributes' \
        --exclude='*.log' \
        --exclude='*.snap' \
        --exclude='.snapcraft' \
        --exclude='*.md' \
        "${SNAPCRAFT_PART_SRC}"/ \
        "${SNAPCRAFT_PART_INSTALL}/app/"

      echo "=== Installing icon ==="
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/meta/gui"

      # Try to find and copy icon
      ICON_FOUND=false
      for icon_path in \
        "${SNAPCRAFT_PART_SRC}/icon.png" \
        "${SNAPCRAFT_PART_SRC}/assets/icon.png" \
        "${SNAPCRAFT_PART_SRC}/resources/icon.png"; do
        if [ -f "${icon_path}" ]; then
          cp -f "${icon_path}" "${SNAPCRAFT_PART_INSTALL}/meta/gui/icon.png"
          echo "Icon copied from: ${icon_path}"
          ICON_FOUND=true
          break
        fi
      done

      if [ "${ICON_FOUND}" = "false" ]; then
        echo "Warning: No icon.png found, creating placeholder"
        printf '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n-\xb4\x00\x00\x00\x00IEND\xaeB`\x82' > "${SNAPCRAFT_PART_INSTALL}/meta/gui/icon.png"
      fi

      echo "=== Creating desktop file ==="
      cat > "${SNAPCRAFT_PART_INSTALL}/meta/gui/mumps-ide.desktop" <<DESKTOP_EOF
      [Desktop Entry]
      Name=MUMPS IDE
      Comment=Professional IDE for MUMPS/M Programming
      Exec=mumps-ide %U
      Icon=\${SNAP}/meta/gui/icon.png
      Terminal=false
      Type=Application
      Categories=Development;IDE;
      StartupWMClass=MUMPS IDE
      DESKTOP_EOF

      echo "=== Creating launcher script ==="
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/bin"

      cat > "${SNAPCRAFT_PART_INSTALL}/bin/mumps-ide" <<'LAUNCHER_EOF'
      #!/bin/sh
      set -eu

      APP_DIR="${SNAP}/app"
      ELECTRON="${APP_DIR}/node_modules/electron/dist/electron"

      # Fix locale
      export LANG="${LANG:-en_US.UTF-8}"
      export LC_ALL="${LC_ALL:-en_US.UTF-8}"

      # GTK theme settings
      export GTK_THEME="${GTK_THEME:-Adwaita}"
      export GTK_USE_PORTAL=0
      export GTK_MODULES=""
      export GTK_PATH="${SNAP}/usr/lib/x86_64-linux-gnu/gtk-3.0"

      # Disable problematic GTK modules
      unset GTK2_RC_FILES

      # Disable GPU sandbox for better compatibility
      export ELECTRON_DISABLE_SANDBOX=1

      # Fix freeze on first launch - disable GPU acceleration if needed
      # Users can remove these flags if their GPU works fine
      export LIBGL_ALWAYS_SOFTWARE=1

      # Git configuration
      export GIT_EXEC_PATH="${SNAP}/usr/lib/git-core"
      export PATH="${SNAP}/usr/bin:${SNAP}/bin:${PATH}"

      # Disable accessibility bridge warnings
      export NO_AT_BRIDGE=1

      # Create config directory if it doesn't exist
      mkdir -p "${SNAP_USER_COMMON}/.config"

      if [ ! -x "${ELECTRON}" ]; then
        echo "ERROR: Electron binary not found at: ${ELECTRON}"
        exit 1
      fi

      # Run electron with optimized flags for snap environment
      exec "${ELECTRON}" "${APP_DIR}" "$@" \
        --no-sandbox \
        --disable-gpu \
        --disable-gpu-sandbox \
        --disable-software-rasterizer \
        --disable-dev-shm-usage \
        --in-process-gpu \
        --disable-accelerated-2d-canvas \
        --num-raster-threads=1 \
        2>&1
      LAUNCHER_EOF

      chmod +x "${SNAPCRAFT_PART_INSTALL}/bin/mumps-ide"

      echo "=== Build complete ==="
      echo "Installed files:"
      ls -la "${SNAPCRAFT_PART_INSTALL}/bin/"
      echo "App directory size:"
      du -sh "${SNAPCRAFT_PART_INSTALL}/app" || true

    stage-packages:
      - libnss3
      - libnspr4
      - libxss1
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libxtst6
      - libappindicator3-1
      - libsecret-1-0
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libdrm2
      - libgbm1
      - libgtk-3-0
      - ca-certificates
      - fonts-liberation
      - fonts-noto
      - fontconfig
      - libfontconfig1
      - adwaita-icon-theme
      - gnome-themes-standard
      - git
      - openssh-client
      - sshpass
      - docker.io
