name: mumps-ide
base: core22
version: '1.0'
summary: MUMPS Language IDE - Professional development environment for MUMPS/M
description: |
  MUMPS Language IDE is a modern, feature-rich integrated development
  environment for MUMPS (M) programming language. Built with Electron
  and Monaco Editor, it provides syntax highlighting, debugging, Docker
  and SSH connectivity, and comprehensive project management.

  Features:
  - Monaco-based code editor with MUMPS syntax highlighting
  - Run and debug MUMPS code with YottaDB integration
  - Docker and SSH connection support
  - Universal Docker mode - works with any container
  - Git integration for version control
  - Integrated terminal with xterm.js
  - Project management and file organization
  - Search and replace across files
  - Extension system for customization

  Developed by Ahmad Alkhalaileh

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  mumps-ide:
    command: bin/mumps-ide
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - browser-support
      - ssh-keys
      - docker
      - removable-media
    environment:
      DISABLE_WAYLAND: '1'
      ELECTRON_TRASH: gio

parts:
  # Main application: copy your whole repo (one level up from snap/)
  # IMPORTANT: no npm install here (avoids ETIMEDOUT + Node version issues in LXD)
  mumps-ide:
    plugin: dump
    source: ..
    organize:
      "*": app/
    prime:
      - -app/.git/**
      - -app/snap/**
      - -app/**/*.log
      - -app/*.log
    override-build: |
      set -eux

      # Ensure icon ends up in the right place for the desktop file
      mkdir -p "$SNAPCRAFT_PART_INSTALL/meta/gui"
      if [ -f "$SNAPCRAFT_PART_SRC/icon.png" ]; then
        cp -f "$SNAPCRAFT_PART_SRC/icon.png" "$SNAPCRAFT_PART_INSTALL/meta/gui/icon.png"
      elif [ -f "$SNAPCRAFT_PART_SRC/app/icon.png" ]; then
        cp -f "$SNAPCRAFT_PART_SRC/app/icon.png" "$SNAPCRAFT_PART_INSTALL/meta/gui/icon.png"
      fi

      # Desktop file
      cat > "$SNAPCRAFT_PART_INSTALL/meta/gui/mumps-ide.desktop" << 'EOF'
      [Desktop Entry]
      Name=MUMPS IDE
      Comment=Professional IDE for MUMPS/M Programming
      Exec=mumps-ide %U
      Icon=${SNAP}/meta/gui/icon.png
      Terminal=false
      Type=Application
      Categories=Development;IDE;
      StartupWMClass=MUMPS IDE
      EOF

      # Launcher script
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      cat > "$SNAPCRAFT_PART_INSTALL/bin/mumps-ide" << 'EOF'
      #!/bin/sh
      # Run Electron from your packaged node_modules
      exec "$SNAP/app/node_modules/.bin/electron" "$SNAP/app" "$@" --no-sandbox --disable-gpu
      EOF
      chmod +x "$SNAPCRAFT_PART_INSTALL/bin/mumps-ide"

      snapcraftctl build

    stage-packages:
      - libnss3
      - libnspr4
      - libxss1
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libxtst6
      - libappindicator3-1
      - libsecret-1-0

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.ahmadalkhalaileh.mumpsIDE
